---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -
scrolling: 
description-p1: Emotion is key to being impactful and moving your audience to action
description-p2: 'Every stage of our process carefully acknowledges your goals and
  identity '
description-p3: Human Horizon Films is a video production company. We are rooted in
  emotional and cinematic stories
baseurl: 
url: https://dearnaomichan.github.io/HHF/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
