---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tahiel@humanhorizonfilms.com - tahiel@humanhorizonfilms.com -
scrolling: 
description-p1: We empower organizations to submerge into their stories to create
  growth and change.
description-p2: Elevate your story and reach new audiences and go beyond the horizon.
description-p3: |
  Human Horizon Films is a video production company rooted in Equity, Authenticity, and Unity. We believe in video as a catalyst for change and
  the synergy of story and service.
baseurl: 
url: https://dearnaomichan.github.io/HHF/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
