---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@humanhorizonfilms.com
description-p1: We empower organizations to express their service stories with emotionally
  rich filmmaking.
description-p2: We believe in sharing the stories of those who serve and inspire others
  to serve others.
description-p3: We believe climate of innovation, authenticity, and meaningful change
  happens at the intersection of many diverse voices.
baseurl: ''
url: https://dearnaomichan.github.io/HHF/
facebook: https://www.facebook.com/humanhorizonfilms
vimeo: https://vimeo.com/hhfilms
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
