---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -
scrolling:
description-p1: Emotion is key to being impactful and moving your audience to dive
  into action
description-p2: Every stage of our process carefully acknowledges your highest goals
  and the identity of your organization
description-p3: Human Horizon Films is a creative storytelling video company. We are
  rooted in emotional and cinematic stories.
baseurl:
url: https://humanhorizonfilms.github.io/hhf/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
