---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -    hello@humanhorizonfilms.com    -
scrolling: 
description-p1: 'We submerge in your needs and make a lasting splash. '
description-p2: Every stage of our process carefully acknowledges your highest goals
  and the identity of your organization
description-p3: 'Stories with a heart are forgettable. '
baseurl: 
url: https://dearnaomichan.github.io/HHF/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
