---
title: Human Horizon Films
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@humanhorizonfilms.com - hello@humanhorizonfilms.com - hello@humanhorizonfilms.com
  - hello@humanhorizonfilms.com -
scrolling: hello@humanhorizonfilms.com
description-p1: We dive into your goals and make a lasting splash
description-p2: Stories with a heart are forgettable
description-p3: Expand your human horizon by reaching a new audience with stories
  from the heart
baseurl: 
url: https://dearnaomichan.github.io/HHF/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
excerpt_separator: "<!--more-->"
